authapp/urls.py
from django.urls import path
from authapp.views import login, register, logout, profile

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
]

basketapp/urls.py
from django.urls import path

from basketapp.views import basket_add, basket_delete

app_name = 'basketapp'

urlpatterns = [
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-delete/<int:id>/', basket_delete, name='basket_delete'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path

from mainapp.views import index, products, test_context

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', products, name='products'),
    path('test-context/', test_context),
]

mainapp/urls.py
from django.urls import path
from mainapp.views import products

app_name = 'mainapp'

urlpatterns = [
    path('', products, name='index'),
    path('<int:id>/', products, name='product')
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatar', blank=True)

basketapp/models.py
from django.db import models

from authapp.models import User
from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=40, unique=True)
    description = models.TextField(blank=True)  # blank=True field can be empty

    class Meta:
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)  # остатки товара на складе
    image = models.ImageField(upload_to='products_images', blank=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    # CASCADE если удалить категорию, то удалятся и все продукты в ней
    # PROTECT нельзя удалить категорию если есть хоть один продукт

    def __str__(self):
        return f'{self.name} | {self.category.name}'

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from authapp.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите почту'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите фамилию'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Подтвердите пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'avatar', 'username', 'email')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from django.contrib import messages

from authapp.forms import UserLoginForm, UserRegisterForm, UserProfileForm
from basketapp.models import Basket


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
        else:
            print(form.errors)
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'authapp/login.html', context)


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Вы успешно зарегистрировались!')
            return HttpResponseRedirect(reverse('auth:login'))

    else:
        form = UserRegisterForm()
    context = {'form': form}

    return render(request, 'authapp/register.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {
        'form': form,
        'baskets': Basket.objects.all(),
    }
    return render(request, 'authapp/profile.html', context)

basketapp/views.py
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse

from mainapp.models import Product
from basketapp.models import Basket


def basket_add(request, product_id=None):
    product = Product.object.get(id=product_id)
    baskets = Basket.object.filter(user=request.user, product=product)

    if not baskets.exists():
        basket = Basket(user=request.user, product=product)
        basket.quantity == 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = baskets.first()
        basket.quantity == 1
        basket.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_delete(request, id=None):
    basket = Basket.objects.get(id=id)
    basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

mainapp/views.py
from django.shortcuts import render


# функции - вьюхи - контроллеры
def index(request):
    context = {'title': 'GeekShop'}
    return render(request, 'mainapp/index.html', context)


def products(request):
    context = {'title': 'GeekShop - каталог'}
    return render(request, 'mainapp/products.html', context)


def test_context(request):
    context = {
        'title': 'geekshop',
        'header': 'Welcome on the site',
        'username': 'Vladimir Pavlukov',
        'products': [
            {'name': 'худи', 'price': '3 050'},
            {'name': 'ботинки', 'price': '4 080'}
        ]
    }
    return render(request, 'mainapp/test-context.html', context)

authapp/templates/authapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop</title>

    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
</body>
</html>

authapp/templates/authapp/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - Авторизация</title>
    <link href="{% static '/css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-5">

                        {% if messages or form.non_field_errors %}
                        <div class="alert
                        {% if messages %} alert-success
                        {% else %} alert-danger
                        {% endif %} alert-dismissible fade show" role="alert" style="margin-top: 50px;">
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% else %}
                                {% for error in form.non_field_errors %}
                                {{ error }}
                            {% endfor %}
                            {% endif%}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}

                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'auth:login' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                            пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="#">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'auth:register' %}">Нужен аккаунт?
                                    Зарегистрируйся!</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static '/js/auth-admin.js' %}"></script>
</body>
</html>

authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block css %}
<link href="{% static '/css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22200%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20200%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_1765bc6c014%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A10pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_1765bc6c014%22%3E%3Crect%20width%3D%22200%22%20height%3D%22200%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2274.421875%22%20y%3D%22104.65%22%3E200x200%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'auth:profile'%}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="userAvatar" size="50">
                            <label class="custom-file-label" for="userAvatar">Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">

            {% include 'basketapp/basket.html' %}

        </div>
    </div>
</div>
{% endblock %}

authapp/templates/authapp/register.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - Регистрация</title>
    <link href="{% static '/css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">

                        {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}

                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'auth:register' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1"
                                                       for="{{ form.first_name.id_for_label }}">Имя</label>
                                                {{ form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                                {{ form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="inputUsername">Имя пользователя</label>
                                            {{ form.username }}
                                        </div>
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес
                                                электронной
                                                почты</label>
                                            {{ form.email }}
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1"
                                                       for="{{ form.password1.id_for_label }}">Пароль</label>
                                                {{ form.password1 }}
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                    пароля</label>
                                                {{ form.password2 }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group mt-4 mb-0">
                                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                    </div>
                                </form>
                            </div>
                            <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'auth:login' %}">Уже есть аккаунт? Авторизоваться</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static '/js/auth-admin.js' %}"></script>
</body>
</html>

basketapp/templates/basketapp/basket.html
{% if baskets %}

    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
    Корзина <span class="badge badge-secondary badge-pill">3</span>
</h4>

    {% for basket in baskets %}

        <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ basket.product.name }}</h5>
            <p class="card-text">{{ basket.product.short_description }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item bg-light">
                <div class="row text-center">
                    <div class="col-lg-4">
                        <input name="basketID" type="number" class="form-control"
                               value="{{ basket.quantity }}" min="0">
                    </div>
                    <div class="col-lg-4">{{ basket.sum }}</div>
                    <div class="col-lg-4">
                        <a href="{% url 'baskets:basket_delete' basket.id %}">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    </div>

    {% endfor %}

    <!--<div class="card mb-3">-->
    <!--    <div class="card-footer">-->
    <!--        <p class="float-left">Итого</p>-->
    <!--        <h4 class="float-right">2 390 руб.</h4>-->
    <!--    </div>-->
    <!--</div>-->
    <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>

{% else %}

    <h4 class="mt-3 mb-3 text-center"> Корзина пуста </h4>

{% endif %}

mainapp/templates/mainapp/Base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>          <!--  <title>GeekShop</title>  -->

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}      <!-- <link href="{% static 'css/index.css' %}" rel="stylesheet">  -->


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="auth/login.html">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="auth/profile.html">Валерий П.
                        <i class="fas fa-user-circle"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="admin/admin.html">
                        <i class="fas fa-users-cog"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Выйти <i class="fas fa-sign-out-alt"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<!--<section>-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-lg-6">-->
<!--                <h1 class="mt-5">GeekShop Store</h1>-->
<!--                <p>-->
<!--                    Новые образы и лучшие бренды на GeekShop Store.-->
<!--                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.-->
<!--                </p>-->
<!--                <button id="start-purchase-btn" type="button" class="btn btn-lg">-->
<!--                    <a id="start-purchase-link" href="products.html">-->
<!--                        Начать покупки-->
<!--                    </a>-->
<!--                </button>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</section>-->

{% block content %} {% endblock %}
{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/mainapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}
    <!--<link href="{% static 'css/index.css' %}" rel="stylesheet">-->
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="auth/login.html">Войти <i class="fas fa-sign-in-alt"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="auth/profile.html">Валерий П.
                        <i class="fas fa-user-circle"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="admin/admin.html">
                        <i class="fas fa-users-cog"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Выйти <i class="fas fa-sign-out-alt"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}
{% endblock %}


{% block footer %}
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mainapp/templates/mainapp/test-context.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{ header }}</h1>
<p>{{ username }}</p>

{% for product in products %}
    <h3>{{ product.name }}</h3>
    {{ product.price }}
{% endfor %}

</body>
</html>